# Generated by Django 4.2.26 on 2025-11-26 00:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=128, unique=True)),
                ('dev_eui', models.CharField(db_index=True, max_length=32)),
                ('dev_addr', models.CharField(blank=True, max_length=32, null=True)),
                ('application_id', models.CharField(max_length=128)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('location_description', models.CharField(blank=True, max_length=255, null=True)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lon', models.FloatField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_rssi', models.FloatField(blank=True, null=True)),
                ('last_snr', models.FloatField(blank=True, null=True)),
                ('last_gateway_id', models.CharField(blank=True, max_length=128, null=True)),
                ('last_fcnt', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('raw_payload', models.TextField(blank=True, null=True)),
                ('decoded_payload_json', models.JSONField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('gateway_id', models.CharField(max_length=128)),
                ('rssi', models.FloatField()),
                ('snr', models.FloatField()),
                ('channel_index', models.IntegerField(blank=True, null=True)),
                ('gateway_lat', models.FloatField(blank=True, null=True)),
                ('gateway_lon', models.FloatField(blank=True, null=True)),
                ('gateway_alt', models.FloatField(blank=True, null=True)),
                ('uplink_token', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_meta', to='devices.device')),
            ],
        ),
    ]
