# Generated by Django 4.2.26 on 2025-11-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='ID urządzenia z TTN (np. fake5)', max_length=64, unique=True)),
                ('dev_eui', models.CharField(help_text='DevEUI urządzenia z TTN', max_length=32, unique=True)),
                ('name', models.CharField(blank=True, help_text='Opcjonalna nazwa urządzenia', max_length=128, null=True)),
                ('description', models.TextField(blank=True, help_text='Opis  urządzenia', null=True)),
                ('last_seen', models.DateTimeField(blank=True, help_text='Data ostatniego odebrania pakietu z TTN', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Czy urządzenie jest aktywne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
