# Generated by Django 4.2.26 on 2025-11-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='f_cnt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
