# Generated by Django 4.2.26 on 2025-11-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_sensorreading_f_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='decoded_payload_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
